name: Build Android

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y make build-essential

    - name: Compile Arasan for Android (ARM64)
      run: |
        cd src
        make -j$(nproc) \
          CC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" \
          CXX="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++" \
          ARCH=aarch64 \
          BUILD_TYPE=neon \
          LIBS="-lc++_shared -lm" \
          CXXFLAGS="-D_LIBCPP_HAS_NO_ALIGNED_ALLOC=1"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: arasan-android-arm64
        path: src/arasanx*
